sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy3.5"

install:
  - pip install .
  - pip install pyspark
  - pip install coverage

script: SPARK_HOME=$(python -c "import os; import pyspark; print(os.path.dirname(pyspark.__file__))") pytest
